group=fun.bm.lophine
mcVersion=26.3
apiVersion=26.3
channel=BETA
clipVersion=1.0.4
weightVersion=1.0.2
# true for release, false for skip release, pre for pre-release
release=pre
# true for push to repo, false for skip push repo, auto for detect by release value
pushRepo=auto

foliaRef=c5928fcf423aa0b823bd0262409f5c923c2bfb86

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
