group=fun.bm.lophine
mcVersion=26.3
apiVersion=26.3
channel=ALPHA
clipVersion=1.0.4
weightVersion=1.0.2
# true for release, false for skip release, pre for pre-release
release=pre
# true for push to repo, false for skip push repo, auto for detect by release value
pushRepo=auto

foliaRef=593ce95419c8f35ad22fb8f09e7a06f2e1d24848

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
