group=fun.bm.lophine
mcVersion=26.3
apiVersion=26.3
channel=ALPHA
clipVersion=1.0.4
weightVersion=1.0.1
# true for release, false for skip release, pre for pre-release
release=pre
# true for push to repo, false for skip push repo, auto for detect by release value
pushRepo=auto

foliaRef=41e8f0056bc3d4f39468e56b712c4992fa811e71

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
